### ISSUE TITLE
Second level namespace violate the naming rules

### ISSUE THREAD

**Issue by purnendudash** [mattan-d/moodle-mod_stream#1]
Please refer to https://moodledev.io/general/development/policies/codingstyle#rules-for-level2

Your custom namespaces like fonts, help, model, pdf, report or privacy violate this naming rule. There are good reasons why it should be followed, mainly to avoid potential conflicts in the future. All these should be under classes/local/ namespace.

https://github.com/mattan-d/moodle-mod_stream/blob/afa6db496584e7ae112c353c68f0053c3a4144cd/classes/crypt/jwt.php#L26

**Comment by danmarsden** [comment]
Thanks purnendu, yes this is a nice thing to fix. 

Note this is not a blocker for plugins db approval.

**Comment by mattan-d** [comment]
Done
