### ISSUE TITLE
external class errors when using Moodle_402 branch

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#10]
At the top of the external.php class in your MOODLE_402 branch adding the following code:
```
use core_external\external_function_parameters;
use core_external\external_value;
use core_external\external_single_structure;
use core_external\external_multiple_structure;
```

Will fix the errors I'm getting:
{
    "error": "Exception - Class \"external_function_parameters\" not found",
    "errorcode": "generalexceptionmessage",
    "stacktrace": "* line 44 of \/mod\/stream\/classes\/external.php: Error thrown\n* line ? of unknownfile: call to mod_stream_external::listing_parameters()\n* line 110 of \/lib\/external\/classes\/external_api.php: call to call_user_func()\n* line 186 of \/lib\/external\/classes\/external_api.php: call to core_external\\external_api::external_function_info()\n* line 83 of \/lib\/ajax\/service.php: call to core_external\\external_api::call_external_function()\n",
    "debuginfo": "\nError code: generalexceptionmessage",
    "reproductionlink": "https:\/\/fraggle.danmarsden.com\/moodle\/course\/modedit.php?add=stream&type&course=2&section=1&return=0&beforemod=0"
}

**Comment by mattan-d** [comment]
Done.
