### ISSUE TITLE
consider adding list of supported branches in the readme file

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#12]
With your plugin having 2 branches, it's often useful to include information on which branch to use in your readme file.

here are a couple of examples:
https://github.com/danmarsden/moodle-mod_attendance?tab=readme-ov-file#branches
https://github.com/catalyst/moodle-auth_saml2?tab=readme-ov-file#branches

not a blocker for approval - just something that will make life a bit easier for people installing your plugin and understanding which branch to use.

**Comment by mattan-d** [comment]
Done.
