### ISSUE TITLE
requires version wrong on 402 branch

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#13]
https://github.com/mattan-d/moodle-mod_stream/blob/MOODLE_402/version.php#L29

that should be the Moodle 4.2 version release - to make it clear that the branch only supports Moodle 4.2 and higher.

more info on that here:
https://moodledev.io/docs/4.4/apis/commonfiles/version.php#requirements

**Comment by mattan-d** [comment]
Done.
