### ISSUE TITLE
Please add a sort order option  by Name, Time Created, View and Size

### ISSUE THREAD

**Issue by shenkarcollage** [mattan-d/moodle-mod_stream#16]
Hey
I it would be very  efficient to add a sort option were to can sort the stream videos by Name, Time Created, View and Size (if possible)
Thank you for the work

**Comment by mattan-d** [comment]
- Added functionality to sort Stream videos based on various criteria: Name, Time Created, Views, and Size
- Implemented sorting logic in the UI to enhance user experience and improve video management efficiency
- Tested sorting options to ensure they work consistently across different video lists

Closes #16
