### ISSUE TITLE
Automatic  fill the title field when adding Stream Mod and choosing a video

### ISSUE THREAD

**Issue by shenkarcollage** [mattan-d/moodle-mod_stream#17]
Hello
It would be very efficient to add automatically the name of the video to the title of the new STREAM mod when adding new Stream.
when adding Stream Mod and choosing a video  the title of the video is embedded anyway to the field video name so I suggest to embed it (with edit  ability) to the title.
see image

![כותרת אוטומטית כשבוחרים סרטון](https://github.com/user-attachments/assets/a74fc674-95e1-4db8-a0eb-172715bc5a1b)

**Comment by mattan-d** [comment]
- Automatically populates the title field with the name of the selected video when adding a new Stream mod.
- Adds flexibility for users by allowing the auto-filled title to be edited.
- Enhances efficiency by embedding the video name directly into the title upon selection, reducing manual input steps.

Resolves #17.
