### ISSUE TITLE
missing permission/login checks in mobile function

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#3]
https://github.com/mattan-d/moodle-mod_stream/blob/master/classes/output/mobile.php#L50

there should probably be a require_login in there but also a check to see if the user can access the cm.

some good examples in the docs here:
https://moodledev.io/general/app/development/plugins-development-guide#step-2-creating-the-main-function

**Comment by mattan-d** [comment]
Done.
