### ISSUE TITLE
external.php 

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#4]
https://github.com/mattan-d/moodle-mod_stream/blob/master/classes/external.php#L46

The phpdocs and descriptions look wrong to me....

"Instance term of guest enrolment plugin" 

while you're fixing that up - maybe making the class phpdoc a bit more useful would be good too "Class for ajax call."

maybe something like "Connect to stream and get meta-data about a video?" - or something that makes more sense? :-)

**Comment by danmarsden** [comment]
Also - it looks like that script can be called anonymously? - so anyone can get a list of all the videos stored on the site? - there's no authentication or capability check in that function.

more info on how to do that with external functions is here (don't use require_login)
https://moodledev.io/docs/4.4/apis/subsystems/external/writing-a-service#context-and-capability-checks

(I'm guessing in your case you would check the system context rather than a course specific level.)

**Comment by mattan-d** [comment]
Thanks for pointing out the issues with the PHPDocs and descriptions. I've made the necessary adjustments. Regarding the PHPDoc for the class, I've updated it to provide a clearer description.
