### ISSUE TITLE
incorrect class name "streamvideo"

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#5]
class streamvideo() isn't quite right.

you could call it class stream_video() or class modstream_video which would be compliant with the "old" rules around class names, but ideally you'd put this into a namespaced class within the "classes" folder under namespace mod_stream;

**Comment by mattan-d** [comment]
The class streamvideo() has been updated to stream_video to follow PascalCase naming conventions. Additionally, I've ensured that it's now properly namespaced under mod_stream and placed within the classes folder, enhancing code organization and maintainability.
