### ISSUE TITLE
files should check if internal OR include config.php

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#6]
the /mobile.php file looks a bit weird. it checks if the file is an internal one (and if not dies) but then it includes config.php - you shouldn't be doing both there.

Either the file is an inline php file (where you include config.php) or it's an internal one with the MOODLE_INTERNAL check.

If you've included config.php you don't need the line which defines all the globals either:
global $PAGE, $DB, $CFG, $OUTPUT;

because you already have them available directly after including config.php

**Comment by danmarsden** [comment]
also - the hardcoded "error" english lang string here doesn't make a lot of sense - you are passing the $preventredirect var so it will trigger an exception.

If the aim is to make it show a "friendly" error instead - like "An error occurred when trying to log you into the site" - that would be better in the lang pack (and would make more sense than simply printing "error" in hard-coded english.

**Comment by mattan-d** [comment]
Done.

**Comment by danmarsden** [comment]
I don't think that file will work correctly in it's current form - looking at the way you use it, I think it probably needs the config.php file included and the internal check remvoed - but probably good to test it (and fix up the session handling stuff as Dani mentioned in the Contrib issue) - I'll hold off testing in the app myself until you've checked that/cleaned it up on your end. - thanks!
