### ISSUE TITLE
missing help strings identifier_help and topic_help

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#7]
https://github.com/mattan-d/moodle-mod_stream/blob/master/mod_form.php#L60
https://github.com/mattan-d/moodle-mod_stream/blob/master/mod_form.php#L66

Moodle automatically looks for the strings with the _help suffix which don't appear to be stored in your lang pack.

**Comment by mattan-d** [comment]
Done.
