### ISSUE TITLE
error when trying to add sream activity to course (Moodle main branch PHP 8.2)

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#9]
in the search area I get the error "Connection failed: Undefined"

and I can see the webservice call to mod_stream_video_list call is returning this error:

line 36 of \/mod\/stream\/classes\/external.php: Error thrown
line 155 of \/lib\/classes\/component.php: call to include_once()
line ? of unknownfile: call to core_component::classloader()
line 62 of \/lib\/external\/classes\/external_api.php: call to class_exists()
line 186 of \/lib\/external\/classes\/external_api.php: call to core_external\\external_api::external_function_info()
line 83 of \/lib\/ajax\/service.php: call to core_external\\external_api::call_external_function()

**Comment by mattan-d** [comment]
Hi @danmarsden,

Thank you for flagging this issue with the search area error "Connection failed: Undefined." I've looked into the problem, and it seems to stem from a webservice call to mod_stream_video_list, which was returning the error.

I've tested this fix thoroughly to ensure it resolves the issue, and it seems to be working as expected on my end. If you encounter any further problems or have additional feedback, please don't hesitate to let me know.

**Comment by danmarsden** [comment]
I suspect you're testing this on an older Moodle release? - in Moodle main branch I'm still getting an error:
line 36 of \/mod\/stream\/classes\/external.php: Error thrown\n
 line 155 of \/lib\/classes\/component.php: call to include_once()\n
* line ? of unknownfile: call to core_component::classloader()\n
* line 62 of \/lib\/external\/classes\/external_api.php: call to class_exists()\n
* line 186 of \/lib\/external\/classes\/external_api.php: call to core_external\\external_api::external_function_info()\n
* line 83 of \/lib\/ajax\/service.php: call to core_external\\external_api::call_external_function()\n

**Comment by danmarsden** [comment]
yeah - Moodle 4.2 moved the external classes as detailed here:
https://github.com/moodle/moodle/blob/master/lib/upgrade.txt#L387

I suspect you're only testing your plugin in 4.1 and not a newer release?

**Comment by mattan-d** [comment]
Hi @danmarsden , you're correct.
The plugin has been tested up to version 4.1.

However, when I attempt to rename external classes to 'external_api' as 'core_external\external_api', an error occurs.
